name: tns_tablet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  # dart_vlc: ^0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/DAZ001.jpg
    - assets/DAZ002.jpg
    - assets/DAZ003.jpg
    - assets/DAZ004.jpg
    - assets/DAZ005.jpg
    - assets/DAZ006.jpg
    - assets/DAZ007.jpg
    - assets/DAZ008.jpg
    - assets/DAZ009.jpg
    - assets/DAZ010.jpg
